version: '2'

services:
  pade:
    build: .
    ports:
      - "5000:5000"
      - "8000:8000"
      - "8001:8001"
      - "3000:3000"
      - "20000:20000"
    tty: true
    stdin_open: true
    command: pade hello_agent.py