version: '2'

services:
  pade:
    build: .
    ports:
      - "5000:5000"
      - "2000:2000"
      - "3000:3000"
      - "4000:4000"
    tty: true
    stdin_open: true
    command: pade hello_agent.py