version: '2'

services:
  pade:
    build: .
    ports:
      - "5000:5000"
      - "8000:8000"
      - "8001:8001"
      - "3000:3000"
      - "20000:20000"
      - "127.0.0.1:5001:5001"
    # tty: true
    # stdin_open: true
    network_mode: "host"
    # command: pade --config_file pade_config.json
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY